version: '3'
services:
  flask:
    build: .
    container_name: backend-flask
    environment:
      # для отладки (при запуске в релиз убрать!)
      - SEARCH_API_KEY=368e7dc00emsh3d4537f301cb786p1fca3djsn60b0fa275902
      ## Позволяет отслеживать процесс работы приложения в командной строке
      - PYTHONUNBUFFERED=True                   
      ##
    # Перезапускаем сервис в случае падения 
    restart: on-failure
    # Прокладывам путь для файлов. Все файлы, которые хранятся у вас в 
    # директории ./backend, появятся в директории контейнера /backend
    volumes:
      - .:.
    # Открываем порт в контейнер
    # Порт, который будет смотреть наружу : порт который используется внутри контейнера
    ports:
      - "5000:5000"
    # command: python main.py